config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  root 'pages#home'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'intro', to: 'pages#intro'
  get 'schedule', to: 'pages#schedule'
  get 'judge', to: 'pages#judge'
  get 'faq', to: 'pages#faq'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  resources :ideas do
    member do
      get :download_attachment
      delete :remove_attachment
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :polls, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :stories, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :galleries, concerns: :commentable
  resources :notices, concerns: :commentable
  delete :likes, to: 'likes#destroy'
  resources :likes
  delete :votes, to: 'votes#destroy'
  resources :votes

  post '/tinymce_assets', to: 'tinymce_assets#create'

  namespace :admin do
    root 'pages#home'
    resources :users do
      member do
        patch :add_admin
        delete :remove_admin
      end
    end
    resources :ideas
  end

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likable
  paginates_per 20

  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true
  belongs_to :parent, class_name: 'Comment', foreign_key: :parent_id, optional: true
  has_many :children, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  scope :order_recent, -> { order(created_at: :desc) }
  scope :order_past, -> { order(created_at: :asc) }
  scope :parents_only, -> { where(parent_id: nil) }
  scope :parents_for_panel, -> { parents_only.order_recent }

  def private_for? someone
    return false unless self.private?
    return true if someone.blank?
    self.user != someone and !someone.admin? and commentable.user != someone
  end

  def parent?
    self.parent_id.nil?
  end

  def deleted?
    self.deleted_at.present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    load_commentable
    @parent_comments = @commentable.comments.parents_for_panel
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    load_commentable
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment
    if @comment.save
      flash[:notice] = '댓글이 게시되었습니다.'
    else
      errors_to_flash(@comment)
      session[:error_comment_body] = @comment.body
    end

    respond_to do |format|
      format.html {
        redirect_to polymorphic_url(@commentable, anchor: params[:comment_form_anchor])
      }
      format.js
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def update
    @comment = Comment.find(params[:id])
    authorize @comment

    @comment.assign_attributes(comment_params)
    if @comment.save
      flash[:success] = '저장되었습니다'
    else
      errors_to_flash(@story)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment

    result = if @comment.parent? and @comment.children.any?
      @comment.touch(:deleted_at)
    else
      @comment.destroy
    end

    if result
      flash[:success] = '삭제되었습니다'
    else
      errors_to_flash(@comment)
    end

    @commentable = @comment.commentable
    @parent_comments = @commentable.comments.parents_for_panel
  end

  private

  def load_commentable
    if params[:commentable_type].present? and params[:commentable_id].present?
      resource = params[:commentable_type].safe_constantize
      if resource.present?
        @commentable = resource.find(params[:commentable_id])
      end
    else
      resource, id = request.path.split('/')[1,2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end
  end

  def comment_params
    params.require(:comment).permit(:body, :private, :parent_id)
  end
end

app/views/comments/_body.html.haml
= simple_format comment.body

app/views/comments/_comment.html.haml
- comment_dom_id = "uid-#{SecureRandom.uuid}"
- counter_dom_id = "rnd-#{SecureRandom.uuid}"
- child_comment_form_id = local_assigns[:child_comment_form_id] || "uid-#{SecureRandom.uuid}" 
.comment{ id: comment_dom_id }
  .comment-meta
    .user.comment-meta-item
      - if comment.deleted? or comment.private_for? current_user
        * * *
      - else
        = comment.user.name
    .created-at.comment-meta-item= static_day_f comment.created_at
    .likes.comment-meta-item
      - unless comment.deleted? or comment.private_for? current_user
        = render 'likes/counter', likable: comment, counter_dom_id: counter_dom_id
  .comment-body
    - if comment.deleted?
      .text-muted
        %i.fa.fa-info-circle
        삭제된 댓글입니다.
    - else 
      - if local_assigns[:show_form]
        - form_dom_id = "uid-#{SecureRandom.uuid}"
        = render 'comments/form', comment: comment, class_name: 'comment-form js-form-validation', form_dom_id: form_dom_id, comment_dom_id: comment_dom_id, list_dom_id: list_dom_id
      - else
        - if comment.private_for? current_user
          .text-muted
            %i.fa.fa-lock
            비밀 댓글입니다.
        - else
          - if comment.private?
            .text-muted
              %i.fa.fa-lock
              비밀 댓글입니다.
          = render 'comments/body', comment: comment
  - unless comment.deleted? or local_assigns[:show_form]
    .comment-control
      -# btn btn-meta btn-meta-detail btn-sm
      - if comment.parent? and comment.commentable.try(:threadable_comment?)
        - if user_signed_in? 
          = link_to '댓글 쓰기', '#', class: 'link js-show-child-comment-form', data: { 'show-child-comment-form-id': child_comment_form_id }
        - else
          = link_to '댓글 쓰기', new_user_session_path, class: 'link js-show-child-comment-form'
      - if policy(comment).edit?
        = link_to '수정', edit_comment_path(comment, comment_dom_id: comment_dom_id, list_dom_id: list_dom_id), remote: true, class: 'link'
      - if policy(comment).destroy?
        = link_to '삭제', comment_path(comment, list_dom_id: list_dom_id, page: params[:page]), method: :delete, remote: true, class: 'link', 'data-confirm': '정말 삭제하시겠습니까?'
      - if (policy(comment).like? or !user_signed_in?) and !comment.private_for?(current_user)
        = render 'likes/button', likable: comment, class_name: 'recomd', counter_dom_id: counter_dom_id
  - if comment.parent?
    .child-comments-list.js-child-comments-list{ class: ('child-comments-list-empty' if comment.children.empty? ) }
      - comment.children.order_past.each do |child_comment|
        = render 'comments/comment', comment: child_comment, list_dom_id: list_dom_id, child_comment_form_id: child_comment_form_id
      = render 'comments/form', commentable: comment.commentable, comment: Comment.new(parent: comment), parent_comment_dom_id: comment_dom_id, class_name: 'comment-form comment-form-child-new js-form-validation collapse', form_dom_id: child_comment_form_id, list_dom_id: list_dom_id

app/views/comments/_form.html.haml
-# LOCAL: commentable comment form_dom_id class_name list_dom_id
- commentable = local_assigns[:commentable] || comment.commentable
- anchro = 'anchor-comment-form'
- anchro += "-#{form_dom_id}" unless comment.parent?
= form_with model: (comment.persisted? ? comment : [commentable, comment]), local: (!comment.persisted? and comment.parent?), id: form_dom_id, class: local_assigns[:class_name], 'data-form-validation-submit-control': "##{form_dom_id} .js-btn-submit" do |f|
  %a.comment-form-anchor{ id: anchro }
  = hidden_field_tag :comment_dom_id, local_assigns[:comment_dom_id]
  = hidden_field_tag :parent_comment_dom_id, local_assigns[:parent_comment_dom_id]
  = hidden_field_tag :list_dom_id, local_assigns[:list_dom_id]
  = hidden_field_tag :comment_form_anchor, 'anchor-comment-form'
  = f.hidden_field :parent_id
  - if !commentable.respond_to?(:private_comments?) or commentable.private_comments?
    .form-group{ style: 'font-size: 14px; position: absolute; top: 18px; right: 0; color: #777;' }
      %label{ }
        = f.check_box :private
        비밀댓글

  .form-group
    = f.text_area :body, value: session[:error_comment_body] || comment.body, class: 'js-comment-cancel-textarea js-show-child-comment-form-focus', data: { 'rule-required': 'true' }
    - session[:error_comment_body] = nil
  .form-group.form-group-submit
    - if comment.persisted?
      = link_to '취소', comment_path(comment, form_dom_id: form_dom_id, list_dom_id: local_assigns[:list_dom_id], comment_dom_id: local_assigns[:comment_dom_id]), remote: true, class: 'cancel', 'data-confirm': '작성하신 것을 모두 지우겠습니까?'
    - elsif comment.parent?
      = link_to '취소', '#', class: 'cancel js-comment-cancel'
    - else
      = link_to '취소', '#', class: 'cancel js-child-comment-cancel'
    = f.submit '등록', class: 'btn btn-primary btn-sm btn-submit js-btn-submit'

app/views/comments/_list.html.haml
.comments-list{ id: list_dom_id }
  - parent_comments.each do |parent_comment|
    = render 'comments/comment', comment: parent_comment, list_dom_id: list_dom_id

app/views/comments/_panel.html.haml
-# LOCAL: commentable comments
- list_dom_id = "uid-#{SecureRandom.uuid}"
- form_dom_id = "uid-#{SecureRandom.uuid}"
.site-comments.js-show-child-comment-form-delegater
  .comment-header
    댓글
  - form_id = "uid-#{SecureRandom.uuid}"
  = render 'comments/form', commentable: commentable, comment: Comment.new, class_name: 'comment-form js-form-validation', form_dom_id: form_dom_id, list_dom_id: list_dom_id
  = render 'comments/list', commentable: commentable, parent_comments: parent_comments, list_dom_id: list_dom_id

app/views/comments/create.js.erb
UnobtrusiveFlash.showFlashFromCookies();
<% if @comment.errors.empty? %>
  $('#<%= params[:parent_comment_dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: (@comment.parent || @comment), list_dom_id: params[:list_dom_id]) %>');
<% end %>

app/views/comments/destroy.js.erb
$('#<%= params['list_dom_id'] %>').replaceWith('<%= j(render 'comments/list', commentable: @commentable, parent_comments: @parent_comments, list_dom_id: params['list_dom_id']) %>');
UnobtrusiveFlash.showFlashFromCookies();

app/views/comments/edit.js.erb
$('#<%= params[:comment_dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, comment_dom_id: params[:comment_dom_id], list_dom_id: params[:list_dom_id], show_form: true) %>');

app/views/comments/index.js.erb
$('#<%= params['list_dom_id'] %>').replaceWith('<%= j(render 'comments/list', commentable: @commentable, parent_comments: @parent_comments, list_dom_id: params['list_dom_id']) %>');
$.scrollTo($('#<%= params['list_dom_id'] %>'), { offset: { top: -100 } });

app/views/comments/show.js.erb
$('#<%= params[:comment_dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, comment_dom_id: params[:comment_dom_id], list_dom_id: params[:list_dom_id]) %>');

app/views/comments/update.js.erb
$('#<%= params[:comment_dom_id] %>').replaceWith('<%= j(render 'comments/comment', comment: @comment, list_dom_id: params[:list_dom_id]) %>');
UnobtrusiveFlash.showFlashFromCookies();