config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  root 'pages#home'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'intro', to: 'pages#intro'
  get 'schedule', to: 'pages#schedule'
  get 'judge', to: 'pages#judge'
  get 'faq', to: 'pages#faq'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  resources :ideas do
    member do
      get :download_attachment
      delete :remove_attachment
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :polls, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :stories, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :galleries, concerns: :commentable
  resources :notices, concerns: :commentable
  delete :likes, to: 'likes#destroy'
  resources :likes
  delete :votes, to: 'votes#destroy'
  resources :votes

  post '/tinymce_assets', to: 'tinymce_assets#create'

  namespace :admin do
    root 'pages#home'
    resources :users do
      member do
        patch :add_admin
        delete :remove_admin
      end
    end
    resources :ideas
  end

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

end

app/models/story.rb
class Story < ApplicationRecord
  include Likable

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  mount_uploader :image, DefaultImageUploader

  ATTACHMENT_MAX_INDEX = 10

  (1..ATTACHMENT_MAX_INDEX).each do |i|
    mount_uploader :"attachment#{i}", PublicDocumentUploader
    validates :"attachment#{i}", file_size: { less_than_or_equal_to: 50.megabytes }
  end

  scope :order_recent, -> { order(created_at: :desc) }
  before_save :update_type

  def valid_attachment_name(index)
    self.send(:"attachment#{index}_name").gsub(/\\+/, "%20")
  end

  def attachment_of(index, postfix = nil)
    con = nil
    con = '_' if postfix.present? and postfix != '!' and postfix != '?'
    self.send(:"attachment#{index}#{con}#{postfix}")
  end

  private

  def update_type
    (1..ATTACHMENT_MAX_INDEX).each do |index|
      if self.attachment_of(index).present? && self.send(:"will_save_change_to_attachment#{index}?")
        self.send(:"attachment#{index}_type=", attachment_of(index).file.content_type)
        self.send(:"attachment#{index}_size=", attachment_of(index).file.size)
      end
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.order_recent.page(params[:page]).per(6)
  end

  def show
    @story = Story.find(params[:id])
    @story.reads_count += 1
    @story.save
  end

  def new
    authorize Story.new
  end

  def create
    @story = Story.new story_params
    authorize @story

    @story.user = current_user

    ActiveRecord::Base.transaction do
      if @story.pin?
        Story.update_all(pin: false)
      end

      if @story.save
        flash[:success] = '게시되었습니다'
        redirect_to @story
      else
        errors_to_flash(@story)
        render :new
      end
    end
  end

  def edit
    @story = Story.find(params[:id])
    authorize @story
  end

  def update
    @story = Story.find(params[:id])
    authorize @story

    @story.assign_attributes(story_params)

    ActiveRecord::Base.transaction do
      if @story.pin?
        Story.update_all(pin: false)
      end

      if @story.save
        flash[:success] = '저장되었습니다'
        redirect_to @story
      else
        errors_to_flash(@story)
        render :new
      end
    end
  end

  def destroy
    @story = Story.find(params[:id])
    authorize @story

    if @story.destroy
      flash[:success] = '삭제되었습니다'
      redirect_to stories_path
    else
      errors_to_flash(@story)
      redirect_to @story
    end
  end

  def remove_image
    @stroy = Story.find(params[:id])
    authorize @stroy, :update?
    @stroy.remove_image!
    if @stroy.save
      flash[:success] = '첨부파일이 삭제되었습니다.'
    else
      flash[:error] = '앗! 뭔가 잘못되었습니다. 잠시 후에 다시 시도해 주세요.'
    end
    redirect_to edit_story_path(@story)
  end

  def remove_attachment
    @story = Story.find(params[:id])
    authorize @story, :update?
    @story.send(:"remove_attachment#{params[:index]}!")
    if @story.save
      flash[:success] = '첨부파일이 삭제되었습니다.'
    else
      flash[:error] = '앗! 뭔가 잘못되었습니다. 잠시 후에 다시 시도해 주세요.'
    end
    redirect_to edit_story_path(@story)
  end

  def download_attachment
    @story = Story.find(params[:id])
    attachment = @story.send(:"attachment#{params[:index]}")
    # local storage
    send_file(attachment.path,
      filename: encoded_attachment_name(@story, params[:index]),
      type: @story.send(:"attachment#{params[:index]}_type"),
      disposition: 'attachment')
  end

  private

  def story_params
    attributes = %i(title body image image_cache pin)
    (1..Story::ATTACHMENT_MAX_INDEX).each do |i|
      attributes += [:"attachment#{i}", :"attachment#{i}_cache"]
    end
    params.require(:story).permit(*attributes)
  end

  def encoded_attachment_name story, index
    filename = story.valid_attachment_name(index)
    if browser.edge?
      filename = CGI::escape(filename)
    elsif browser.ie?
      filename = URI::encode(filename)
    elsif ENV['FILENAME_ENCODING'].present?
      filename = filename.encode('UTF-8', ENV['FILENAME_ENCODING'], invalid: :replace, undef: :replace, replace: '?')
    end
    filename
  end
end

app/views/stories/_form.html.haml
- story ||= (@story || Story.new)
.site-content-container
  .site-form
    %h2 소식 #{ story.persisted? ? '수정' : '글쓰기' }
    = form_with model: story do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'tinymce js-tinymce', 'data-toolbar': 'styleselect | bold italic | undo redo | image | link media', 'data-content-css': asset_url('tinymce_content.css')
      .form-group
        = f.label :image
        - if f.object.image? and f.object.persisted?
          %p.help-block
            = image_tag f.object.image.lg.url, style: 'max-width: 100px; vertical-align: bottom'
            &nbsp;
            = link_to '파일 삭제', remove_image_story_path(f.object), method: :delete, class: 'btn btn-outline-secondary btn-sm'
        .custom-file
          = f.file_field :image, class: 'form-control-file custom-file-input js-custom-file-input', lang: 'ko'
          = f.hidden_field :image_cache
          = f.label :image, class: 'custom-file-label js-custom-file-label' do
            - if f.object.image?
              새로운 이미지 선택...
            - else
              이미지 선택...
      - (1..Story::ATTACHMENT_MAX_INDEX).each do |i|
        .form-group
          = f.label :"attachment#{i}"
          .row
            .col-12.col-sm-6
              .custom-file
                = f.file_field :"attachment#{i}", class: 'form-control-file custom-file-input js-custom-file-input', lang: 'ko'
                = f.hidden_field :"attachment#{i}_cache"
                = f.label :"attachment#{i}", class: 'custom-file-label js-custom-file-label' do
                  - if f.object.attachment_of(i, '?')
                    새로운 파일 선택...
                  - else
                    파일 선택...
            .col-12.col-sm-6
              - if f.object.attachment_of(i, '?')
                %p.help-block.story-file-help-block
                  = link_to f.object.attachment_of(i, :url), target: '_blank', class: 'download text-decoration-none' do
                    %i.fa.fa-file
                    = f.object.attachment_of(i, :name)
                    다운로드
                  - if f.object.persisted?
                    %span.d-block.d-sm-none
                    = link_to '파일 삭제', remove_attachment_story_path(f.object, index: i), method: :delete, class: 'btn btn-outline-secondary btn-sm remove-btn'

      .form-group.form-group-submit
        = f.submit (f.object.persisted? ? "수정" : "등록"), class: 'btn btn-primary js-confirm-btn'
        %a{href: stories_path, class: 'btn btn-outline-secondary'} 취소

app/views/stories/_story.html.haml
.story.site-card-list-item.cursor-pointer.js-link{ 'data-url': story_path(story, page: params[:page]) }
  .img{ class: ('img-default' unless story.image?), style: "background-image: url(#{ story.image? ? story.image.lg.url : asset_url('no-img.png') });" }
  .title= story.title
  .info
    %span.date
      = static_day_f(story.created_at)
    .counts
      %span.count.like{ class: ('active' if story.like_by?(current_user)) }
        %i.fa{ class: (story.like_by?(current_user) ? 'fa-heart' : 'fa-heart-o' ) }
        = story.likes_count
      - if story.comments_count != 0
        %span.count.comment
          %i.fa.fa-comment-o
          = story.comments_count

app/views/stories/edit.html.haml
- content = capture do
  = render 'stories/form', story: @story
= render 'layouts/story', content: content

app/views/stories/index.html.haml
- content = capture do
  .site-content-container
    .site-btn-notice-container.d-flex.flex-sm-row.justify-content-sm-between.align-items-sm-center.flex-column.justify-content-between.align-items-center
      .desc
        코리아 챌린지의 새 소식과
        %br.d-block.d-sm-none
        공지사항을 알려드립니다.
      - if policy(Story).new?
        %a.btn.btn-white.btn-outline-primary{ href: new_story_path } 글쓰기
    - if @stories.any?
      .site-line-list-container.mb-5
        .site-card-list
          = render @stories
        = paginate @stories
    - elsif @stories.total_count <= 0
      .site-basic-contents
        .text-center.text-muted.mb-5
          새 소식과 공지사항을 준비 중입니다.

= render 'layouts/story', content: content

app/views/stories/new.html.haml
- content = capture do
  = render 'stories/form'
= render 'layouts/story', content: content

app/views/stories/show.html.haml
- content = capture do
  .site-content-container
    .site-detail
      %h2= @story.title
      .info
        %span.date
          = static_day_f(@story.created_at)
        - if @story.reads_count != 0
          %span.view
            조회
            = @story.reads_count
        - if @story.comments_count != 0
          %span.view
            댓글
            = @story.comments_count
      .body.js-fit-vids

        %p!= @story.body

        %ul.list-unstyled.downloads
          - (1..Story::ATTACHMENT_MAX_INDEX).each do |index|
            - if @story.attachment_of(index, '?')
              %li.download
                = link_to download_attachment_story_path(@story, index: index) do
                  %i.fa.fa-download
                  #{@story.attachment_of(index, :name)}
                %span.text-muted #{number_to_human_size @story.attachment_of(index, :size)}
      .btns.justify-content-between
        .btns-left{ style: 'flex: 3' }
          = render 'likes/button', likable: @story
          %a.btn.btn-meta.btn-meta-detail.facebook{href: "https://www.facebook.com/sharer/sharer.php?u=#{polymorphic_url(@story)}", target: '_blank', title: '공유하기'}
            %i.fa.fa-share-alt
            %span 공유
          %a.btn.btn-meta.btn-meta-detail.js-clipboard{'data-clipboard-text': polymorphic_url(@story)}
            %i.fa.fa-link
            %span 주소복사
          - manage_menus = capture do
            - if policy(@story).edit?
              %li= link_to '수정', [:edit, @story], class: 'dropdown-item'
            - if policy(@story).destroy?
              %li= link_to '삭제', @story, method: :delete, class: 'dropdown-item', 'data-confirm': '정말 삭제하시겠습니까?'
          - if manage_menus.present?
            .dropdown.btn.btn-meta.btn-meta-detail.d-none.d-sm-inline-block
              %a(data-toggle="dropdown")
                더 보기
                %i.fa.fa-angle-down
              %ul.dropdown-menu.dropdown-menu-right
                = manage_menus
        .btns-right
          %a.list{href: stories_path(page: params[:page])}
            목록
            %i.fa.fa-angle-right

      = render 'comments/panel', commentable: @story, parent_comments: @story.comments.parents_for_panel
= render 'layouts/story', content: content