config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  root 'pages#home'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'intro', to: 'pages#intro'
  get 'schedule', to: 'pages#schedule'
  get 'judge', to: 'pages#judge'
  get 'faq', to: 'pages#faq'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  resources :ideas do
    member do
      get :download_attachment
      delete :remove_attachment
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :polls, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :stories, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :galleries, concerns: :commentable
  resources :notices, concerns: :commentable
  delete :likes, to: 'likes#destroy'
  resources :likes
  delete :votes, to: 'votes#destroy'
  resources :votes

  post '/tinymce_assets', to: 'tinymce_assets#create'

  namespace :admin do
    root 'pages#home'
    resources :users do
      member do
        patch :add_admin
        delete :remove_admin
      end
    end
    resources :ideas
  end

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable,
  # :recoverable, :validatable
  devise :database_authenticatable, :registerable,
         :rememberable, :omniauthable

  has_one :idea, dependent: :destroy
  has_many :notices, dependent: :destroy
  has_many :stories, dependent: :restrict_with_error
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates_format_of       :email, with: Devise.email_regexp, allow_blank: true, if: :will_save_change_to_email?
  validates_presence_of     :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of       :password, within: Devise.password_length, allow_blank: true
  validates :uid, uniqueness: { scope: [:provider] }

  before_validation :downcase_email

  scope :order_recent, -> { order(created_at: :desc) }
  scoped_search on: [:name, :email]

  mount_uploader :profile_image, DefaultImageUploader


  def self.find_for_omniauth(provider, uid)
    where(provider: provider, uid: uid).first
  end

  def self.parse_omniauth(data, params)
    result = { provider: data['provider'],
      uid: data['uid'],
      email: data['info']['email'],
      image: data['info']['image'],
      name: data['info']['name'] || data['info']['nickname'] }

    remember_me = params.try(:fetch, "remember_me", false)
    result[:remember_me] = remember_me
    result
  end

  def self.find_or_initialize_for_omniauth(parsed_data)
    user = User.find_or_initialize_by(provider: parsed_data[:provider], uid: parsed_data[:uid]) do |user|
      user.email = parsed_data[:email]
      user.name = parsed_data[:name] || user.email
      user.password = Devise.friendly_token[0,20]
      user.remote_profile_image_url = parsed_data[:image]
    end
    user.remember_me = parsed_data[:remember_me]
    user
  end

  def email_required?
    false
  end

  def admin?
    self.admin or fixed_admin?
  end

  def fixed_admin?
    %w(contact@parti.xyz foroso@gmail.com).include?(self.email)
  end

  def confirmation?
    confirmation_terms == true and confirmation_privacy == true and confirmation_offer == true
  end

  def cancelable?
    !self.stories.exists?
  end

  private

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def downcase_email
    if self.email.present?
      self.email = self.email.downcase
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.order_recent.page(params[:page]).per(50)
    if params[:q].present?
      query = params[:q]
      if query.present?
        @users = @users.search_for(query)
      end
    end
  end

  def add_admin
    @user = User.find(params[:id])
    @user.admin = true

    if @user.save
    else
      errors_to_flash(@user)
    end
    redirect_to admin_users_path(page: params[:page])
  end

  def remove_admin
    @user = User.find(params[:id])
    @user.admin = false

    if @user.save
    else
      errors_to_flash(@user)
    end
    redirect_to admin_users_path(page: params[:page])
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token
  prepend_before_action :require_no_authentication, only: [:facebook, :kakao, :naver]

  def facebook
    run_omniauth
  end

  def naver
    run_omniauth
  end

  def kakao
    run_omniauth
  end

  def failure
    redirect_to root_path
  end

  def failure
    logger.fatal "Omniauth Fail : kind: OmniAuth::Utils.camelize(failed_strategy.try(:name)), reason: #{failure_message}"
    logger.fatal "Omniauth Env : #{request.env.inspect}"

    set_flash_message(:notice, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.try(:name)),
      reason: failure_message) if is_navigational_format?
    redirect_to root_path
  end

  private

  def run_omniauth
    parsed_data = User.parse_omniauth(request.env["omniauth.auth"], request.env["omniauth.params"])

    @user = User.find_or_initialize_for_omniauth(parsed_data)
    if @user.new_record?
      if @user.save
      else
        set_flash_message(:notice, :failure, kind: @user.provider, reason: @user.errors.full_messages.to_sentence)
        redirect_to root_path
        return
      end
    end

    if @user.confirmation?
      set_flash_message(:notice, :success, kind: @user.provider)
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = '더 진행하기 위해 약관에 동의하세요.'

      scope = Devise::Mapping.find_scope!(@user)
      sign_in(scope, @user)
      redirect_to users_confirm_form_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def cancel
    redirect_to :root_path and return unless user_signed_in?

    if current_user.destroy
      sign_out current_user
      flash[:success] = '탈퇴되었습니다. 다음에 다시 만나요.'
    else
      flash[:error] = '탈퇴 중에 오류가 발생했습니다. 잠시 후에 다시 시도해 주세요.'
    end

    redirect_to root_path
  end

  def confirm_form
  end

  def confirm
    render_404 and return unless user_signed_in?

    current_user.confirmation_terms = (params[:confirmation_terms] == "y")
    current_user.confirmation_privacy = (params[:confirmation_privacy] == "y")
    current_user.confirmation_offer = (params[:confirmation_offer] == "y")
    current_user.confirmation_mailing = (params[:confirmation_mailing] == "y")
    current_user.save

    flash[:success] = '동의 절차가 완료되었습니다.'
    redirect_to after_sign_in_path_for(current_user)
  end
end

app/views/admin/users/index.html.haml
= render 'admin/navbar'

%section.section-admin-page
  .container
    .clearfix
      %h4.float-left 회원관리

      .float-right
        = form_with url: admin_users_path, method: :get, local: true do |f|
          - if params[:q].present?
            = link_to admin_users_path do
              전체 보기
            &nbsp;
            \/
            &nbsp;
          = f.text_field :q, value: params[:q], placeholder: '이름이나 이메일', style: 'height: 30px'
          = f.submit '찾기', style: 'height: 30px; border: 1px solid black; padding: 0 10px;'

    %table.table.table-striped#users
      %thead
        %tr
          %th{width: '5%'} #
          %th{width: '20%'} 닉네임
          %th{width: '20%'} 이메일
          %th{width: '10%'} SNS
          %th{width: '20%'} 가입일
          %th{width: '15%'} 관리자
          %th{width: '10%'} 참가신청
      %tbody
        - @users.each do |user|
          %tr
            %td= user.id
            %td= user.name
            %td= (user.email.present? ? link_to(user.email, "mailto:#{user.email}") : '')
            %td= user.provider
            %td= human_datetime_f(user.created_at)
            %td
              = '관리자' if user.admin?
              - if user.admin? and !user.fixed_admin?
                = link_to remove_admin_admin_user_path(user), method: :delete, class: 'text-nowrap' do
                  %span.text-danger
                    %i.fa.fa-window-close-o
                    권한삭제
              - unless user.admin?
                = link_to add_admin_admin_user_path(user), method: :patch, class: 'text-nowrap' do
                  %i.fa.fa-plus-square
                  권한지정
            %td
              - if user.idea.present?
                = link_to admin_idea_path(user.idea) do
                  - if user.idea.submitted?
                    신청서
                  - else
                    .text-muted
                      임시저장
          %tr
            %td.text-primary.text-nowrap 예선투표
            %td{ colspan: 6 }
              - any_voted = false
              - Poll.order(title: :asc).each do |poll|
                - if poll.voted_by?(user)
                  - any_voted = true
                  %span.voted-poll.text-nowrap{ style: 'background-color: #eee; margin-right: 10px; padding: 2px 10px' }
                    = poll.title
              - unless any_voted
                %span.voted-poll.text-muted .

    = paginate @users