config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  root 'pages#home'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'intro', to: 'pages#intro'
  get 'schedule', to: 'pages#schedule'
  get 'judge', to: 'pages#judge'
  get 'faq', to: 'pages#faq'

  delete :cancel_current_user, to: 'users#cancel'
  delete :confirm_user, to: 'users#confirm'
  post 'users/confirm', to: 'users#confirm'
  get 'users/confirm_form', to: 'users#confirm_form'

  resources :ideas do
    member do
      get :download_attachment
      delete :remove_attachment
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end
  resources :polls, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :stories, concerns: :commentable do
    member do
      get :download_attachment
      delete :remove_image
      delete :remove_attachment
    end
  end
  resources :galleries, concerns: :commentable
  resources :notices, concerns: :commentable
  delete :likes, to: 'likes#destroy'
  resources :likes
  delete :votes, to: 'votes#destroy'
  resources :votes

  post '/tinymce_assets', to: 'tinymce_assets#create'

  namespace :admin do
    root 'pages#home'
    resources :users do
      member do
        patch :add_admin
        delete :remove_admin
      end
    end
    resources :ideas
  end

  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/401', to: 'errors#unauthorized', via: :all, as: :error_401
  match '/403', to: 'errors#forbidden', via: :all, as: :error_403
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  after_action :prepare_unobtrusive_flash
  before_action :prepare_meta_tags, if: -> { request.get? and !Rails.env.test? }
  before_action :check_confirmed_user

  include Pundit
  protect_from_forgery

  def errors_to_flash(model)
    flash[:notice] = errors_to_str(model, '<br>').html_safe
  end

  def errors_to_str(model, br)
    return if model.errors.empty?
    result ||= ""
    result += model.errors.full_messages.join(br)
    result
  end

  if Rails.env.production? or Rails.env.staging?
    rescue_from ActionController::RoutingError, ActiveRecord::RecordNotFound, ActionController::UnknownFormat do |exception|
      render_404
    end
    rescue_from ActionController::InvalidCrossOriginRequest, ActionController::InvalidAuthenticityToken do |exception|
      render_403
    end
  end
  rescue_from Pundit::NotAuthorizedError do |exception|
    policy_name = exception.policy.class.to_s.underscore
    if user_signed_in?
      flash[:alert] = t("#{policy_name}.#{exception.query}", scope: "pundit", default: :default)
    else
      flash[:alert] = t("unsigned", scope: "pundit", default: :default)
    end
    render_401
  end

  def render_401
    self.response_body = nil
    respond_to do |format|
      format.html { redirect_to error_401_path }
      format.js { head 401 }
    end
  end

  def render_403
    self.response_body = nil
    respond_to do |format|
      format.html { redirect_to error_403_path }
      format.js { head 403 }
    end
  end

  def render_404
    self.response_body = nil
    respond_to do |format|
      format.html { redirect_to error_404_path }
      format.js { head 404 }
    end
  end

  def render_500
    self.response_body = nil
    respond_to do |format|
      format.html { redirect_to error_500_path }
      format.js { head 500 }
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  def storable_location?
    (request.get? and is_navigational_format? and
      !devise_controller? and !request.xhr? and
      controller_name != 'errors' and !devise_controller? and
      !(controller_name == 'users' and action_name == 'confirm') and
      !(controller_name == 'users' and action_name == 'confirm_form') and
      !(controller_name == 'users' and action_name == 'cancel') and
      !(controller_name == 'pages' and action_name == 'privacy') and
      !(controller_name == 'pages' and action_name == 'terms'))
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def respond_modal_with(*args, &block)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &block
  end

  private

  def check_confirmed_user
    return unless user_signed_in?

    if !current_user.confirmation?
      if !devise_controller? and
          !(controller_name == 'users' and action_name == 'confirm') and
          !(controller_name == 'users' and action_name == 'confirm_form') and
          !(controller_name == 'users' and action_name == 'cancel')
        flash[:notice] = '더 진행하기 위해 약관에 동의하세요.'
        redirect_to users_confirm_form_path and return
      end
    end
  end

  def prepare_meta_tags(options={})
    set_meta_tags build_meta_options(options)
  end

  def build_meta_options(options)
    unless options.nil?
      options.compact!
      options.reverse_merge! default_meta_options
    else
      options = default_meta_options
    end

    current_url = request.url
    og_description = (helpers.strip_tags options[:description]).truncate(160)
    {
      title:       options[:title],
      reverse:     true,
      image:       helpers.asset_url(options[:image]),
      description: options[:description],
      keywords:    options[:keywords],
      canonical:   current_url,
      og: {
        url: current_url,
        title: options[:og_title] || options[:title],
        image: helpers.asset_url(options[:image]),
        description: og_description,
        type: 'website'
      }
    }.reject{ |_,v| v.nil? }
  end

  def default_meta_options
    {
      title: "2019 코리아 챌린지 : 국민 제안, 국민 선택",
      description: "한국사회를 변화시킬 국민참여 아이디어 경연대회! 상금 1,919만원의 주인공이 되세요!",
      keywords: "삼일운동, 정치, 민주주의, 공론장",
      image: helpers.asset_url("kochal_seo.png"),
      twitter_card_type: "summary_card"
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_style?
    !current_page?('/privacy') and
    !current_page?('/terms')
  end

  def body_class
    dasherized_controller_name = params[:controller].gsub(/\//, '--')
    arr = ["app-#{dasherized_controller_name}", "app-#{dasherized_controller_name}-#{params[:action]}"]
    arr.join(' ')
  end

  def static_day_f(date)
    date.strftime("%Y.%m.%d")
  end

  def human_datetime_f(date)
    date.strftime("%Y년 %m월 %d일 %H:%M")
  end

  def is_kakao_talkable?
    browser.device.mobile?
  end

  def excerpt(text, options = {})
    return text if text.blank?

    options[:length] = 130 unless options.has_key?(:length)
    result = strip_tags(text)
    return result if result.blank?

    result = HTMLEntities.new.decode(result)
    return result.truncate(options[:length], options)
  end
end

app/views/application/_favicons.html.haml
%link{href: asset_url("favicons/apple-touch-icon.png"), rel: "apple-touch-icon", sizes: "180x180"}
%link{href: asset_url("favicons/favicon-32x32.png"), rel: "icon", sizes: "32x32", type: "image/png"}
%link{href: asset_url("favicons/favicon-16x16.png"), rel: "icon", sizes: "16x16", type: "image/png"}
%link{color: "#5bbad5", href: asset_url("favicons/safari-pinned-tab.svg"), rel: "mask-icon"}
%meta{content: "#ffffff", name: "theme-color"}

app/views/application/_footer.html.haml
%footer.site-footer.js-main-navbar-nav-exclude
  .container
    .site-footer-container
      .logo
        = image_tag 'home/logo.png', style: 'height: 56px;'
        .logo-desc
          대통령 직속
          %br.d-block.d-md-none
          3.1운동 및 대한민국 임시정부수립
          %br.d-block.d-md-none
          100주년 기념사업추진위원회
      .site-meta
        .item
          %i.fa.fa-phone
          %a(href='tel:0269592003') 02 6959 2003
        %br.d-block.d-sm-none
        .item
          %i.fa.fa-envelope
          %a(href='mailto:2019korchall@gmail.com') 2019korchall@gmail.com
        %br.d-block.d-md-none
        .item
          %a{ href: terms_path } 이용약관
        .item
          %a{ href: privacy_path } 개인정보처리방침
        .item
          %a{ href: "https://www.facebook.com/together100years", target: '_blank' }
            = image_tag "share-facebook.png", style: 'height: 24px; width: 24px;'

      - if user_signed_in? and current_user.admin?
        %hr
        .site-meta
          .item
            %a{ href: admin_root_path } 운영

app/views/application/_navbar.html.haml
%nav.navbar.navbar-kc.navbar-expand-lg.navbar-light#js-main-navbar
  .container
    .navbar-brand-container
      %a.navbar-brand{ href: root_path }
        = image_tag 'home/logo.png', style: 'height: 40px; vertical-align: text-bottom;'
        %span{ style: 'font-size: 18px; font-weight: bold;' } 코리아챌린지
      %button.navbar-toggler.navbar-toggler-noborder(aria-controls="js-main-navbar-nav" aria-expanded="false" aria-label="Toggle navigation" data-target="#js-main-navbar-nav" data-toggle="collapse" type="button")
        %span.navbar-toggler-icon
    #js-main-navbar-nav.collapse.navbar-collapse
      %ul.navbar-nav.navbar-nav-contents.mx-lg-auto{ class: ('navbar-nav-contents-user-signed-in' if user_signed_in?) }

        - active_intro = ( current_page?('/intro') or current_page?('/about') or current_page?('/schedule') or params[:controller] == 'ideas' )
        %li.nav-item
          %a.nav-link.js-subnav-xs{ href: intro_path, class: ( active_intro ? 'active nav-arrow-up' : 'nav-arrow-down' ), 'data-subnav': '#navsub-intro' } 공모개요
        %ul.navbar-nav.navbar-subnav#navsub-intro{ class: ('collapse' unless active_intro) }
          %li.nav-item
            %a.nav-link{ href: intro_path, class: ('active' if current_page?('/intro') ) } 공모 안내
          %li.nav-item
            %a.nav-link{ href: about_path, class: ('active' if current_page?('/about') ) } 이런 아이디어를 기다립니다
          %li.nav-item
            %a.nav-link{ href: schedule_path, class: ('active' if current_page?('/schedule') ) } 대회 일정
        - active_polls = controller_name == 'polls'
        - current_poll_round_slug = @poll.round_slug if @poll.present?
        - current_poll_round_slug ||= params[:round_slug] if params[:round_slug].present?
        - current_poll_round_slug ||= Poll::DEFALUT_ROUND_SLUG

        %li.nav-item
          %a.nav-link.js-subnav-xs{ href: polls_path, class: ( active_polls ? 'active nav-arrow-up' : 'nav-arrow-down' ), 'data-subnav': '#navsub-polls' } 온라인 국민투표
        %ul.navbar-nav.navbar-subnav#navsub-polls{ class: ('collapse' unless active_polls) }
          %li.nav-item
            %a.nav-link{ href: polls_path(round_slug: 'final'), class: ('active' if active_polls and current_poll_round_slug == 'final' ) } 본선
          %li.nav-item
            %a.nav-link{ href: polls_path(round_slug: 'pre'), class: ('active' if active_polls and current_poll_round_slug == 'pre' ) } 예선

        %li.nav-item
          %a.nav-link{ href: judge_path, class: ('active' if current_page?('/judge') ) } 국민판정단 신청
        %li.nav-item
          %a.nav-link{ href: galleries_path, class: ('active' if controller_name == 'galleries' ) } 경연현장
        - active_stories = (%w(stories notices).include?(params[:controller]) or current_page?('/faq'))
        %li.nav-item
          %a.nav-link.js-subnav-xs{ href: stories_path, class: ( active_stories ? 'active nav-arrow-up' : 'nav-arrow-down' ), 'data-subnav': '#navsub-stories' } 소통광장
        %ul.navbar-nav.navbar-subnav#navsub-stories{ class: ('collapse' unless active_stories) }
          %li.nav-item
            %a.nav-link{ href: stories_path, class: ('active' if params[:controller] == 'stories' ) } 소식
          %li.nav-item
            %a.nav-link{ href: notices_path, class: ('active' if params[:controller] == 'notices' ) } 국민의견
          %li.nav-item
            %a.nav-link{ href: faq_path, class: ('active' if current_page?('/faq') ) } FAQ
      %ul.navbar-nav.navbar-nav-utils{ class: ('navbar-nav-utils-user-signed-in' if user_signed_in?) }
        - if user_signed_in?
          %li.nav-item.dropdown
            %a#user-dropdown.nav-link.dropdown-toggle(aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#")= current_user.name
            %ul.dropdown-menu.dropdown-menu-right(aria-labelledby="user-dropdown")
              - if current_user.idea.present?
                %li= link_to '신청서 수정', new_idea_path, class: 'dropdown-item'
              - else
                %li= link_to '신청하기', new_idea_path, class: 'dropdown-item'
              %li= link_to '로그아웃', destroy_user_session_path, method: :delete, class: 'dropdown-item'
              - if current_user.cancelable?
                %li= link_to "탈퇴", cancel_current_user_path, method: :delete, class: 'dropdown-item', 'data-confirm': '탈퇴하시겠습니까? 모든 데이터가 삭제됩니다.'
              - else
                %li.text-muted
                  %a.dropdown-item(href='#')
                    탈퇴 불가
                    %small.text-muted 작성한 소식을 먼저 지워 주세요.
        - else
          %li.nav-item
            %a.nav-link.btn.btn-outline-primary.nav-btn.cursor-pointer{ href: new_user_session_path } 로그인
          %li.nav-item
            %a.nav-link.btn.btn-outline-primary.ml-2.nav-btn.cursor-pointer{ href: new_user_registration_path } 회원가입